# Generated by Django 3.2 on 2021-04-18 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('max_points', models.FloatField(null=True)),
                ('my_points', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic', to='score.subject')),
                ('r1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r1', to='score.subject')),
                ('r2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r2', to='score.subject')),
            ],
        ),
    ]
